/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateGroupRouteImport } from './routes/create/group'
import { Route as CreateExpenseRouteImport } from './routes/create/expense'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as accountSettingsRouteImport } from './routes/(account)/settings'
import { Route as accountActivityRouteImport } from './routes/(account)/activity'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGroupRoute = CreateGroupRouteImport.update({
  id: '/create/group',
  path: '/create/group',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExpenseRoute = CreateExpenseRouteImport.update({
  id: '/create/expense',
  path: '/create/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const accountSettingsRoute = accountSettingsRouteImport.update({
  id: '/(account)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const accountActivityRoute = accountActivityRouteImport.update({
  id: '/(account)/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/activity': typeof accountActivityRoute
  '/settings': typeof accountSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/create/expense': typeof CreateExpenseRoute
  '/create/group': typeof CreateGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/activity': typeof accountActivityRoute
  '/settings': typeof accountSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/create/expense': typeof CreateExpenseRoute
  '/create/group': typeof CreateGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/(account)/activity': typeof accountActivityRoute
  '/(account)/settings': typeof accountSettingsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/create/expense': typeof CreateExpenseRoute
  '/create/group': typeof CreateGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/activity'
    | '/settings'
    | '/login'
    | '/signup'
    | '/create/expense'
    | '/create/group'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/activity'
    | '/settings'
    | '/login'
    | '/signup'
    | '/create/expense'
    | '/create/group'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(account)/activity'
    | '/(account)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/create/expense'
    | '/create/group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  accountActivityRoute: typeof accountActivityRoute
  accountSettingsRoute: typeof accountSettingsRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  CreateExpenseRoute: typeof CreateExpenseRoute
  CreateGroupRoute: typeof CreateGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/group': {
      id: '/create/group'
      path: '/create/group'
      fullPath: '/create/group'
      preLoaderRoute: typeof CreateGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/expense': {
      id: '/create/expense'
      path: '/create/expense'
      fullPath: '/create/expense'
      preLoaderRoute: typeof CreateExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/settings': {
      id: '/(account)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof accountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/activity': {
      id: '/(account)/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof accountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  accountActivityRoute: accountActivityRoute,
  accountSettingsRoute: accountSettingsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  CreateExpenseRoute: CreateExpenseRoute,
  CreateGroupRoute: CreateGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
