/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettleUpRouteImport } from './routes/settle-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndividualExpensesRouteImport } from './routes/individual-expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateGroupRouteImport } from './routes/create-group'
import { Route as AddExpenseRouteImport } from './routes/add-expense'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as AddExpenseUserIdRouteImport } from './routes/add-expense.$userId'

const SettleUpRoute = SettleUpRouteImport.update({
  id: '/settle-up',
  path: '/settle-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualExpensesRoute = IndividualExpensesRouteImport.update({
  id: '/individual-expenses',
  path: '/individual-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGroupRoute = CreateGroupRouteImport.update({
  id: '/create-group',
  path: '/create-group',
  getParentRoute: () => rootRouteImport,
} as any)
const AddExpenseRoute = AddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AddExpenseUserIdRoute = AddExpenseUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AddExpenseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-expense': typeof AddExpenseRouteWithChildren
  '/create-group': typeof CreateGroupRoute
  '/dashboard': typeof DashboardRoute
  '/individual-expenses': typeof IndividualExpensesRoute
  '/settings': typeof SettingsRoute
  '/settle-up': typeof SettleUpRoute
  '/add-expense/$userId': typeof AddExpenseUserIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-expense': typeof AddExpenseRouteWithChildren
  '/create-group': typeof CreateGroupRoute
  '/dashboard': typeof DashboardRoute
  '/individual-expenses': typeof IndividualExpensesRoute
  '/settings': typeof SettingsRoute
  '/settle-up': typeof SettleUpRoute
  '/add-expense/$userId': typeof AddExpenseUserIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-expense': typeof AddExpenseRouteWithChildren
  '/create-group': typeof CreateGroupRoute
  '/dashboard': typeof DashboardRoute
  '/individual-expenses': typeof IndividualExpensesRoute
  '/settings': typeof SettingsRoute
  '/settle-up': typeof SettleUpRoute
  '/add-expense/$userId': typeof AddExpenseUserIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/add-expense'
    | '/create-group'
    | '/dashboard'
    | '/individual-expenses'
    | '/settings'
    | '/settle-up'
    | '/add-expense/$userId'
    | '/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/add-expense'
    | '/create-group'
    | '/dashboard'
    | '/individual-expenses'
    | '/settings'
    | '/settle-up'
    | '/add-expense/$userId'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/add-expense'
    | '/create-group'
    | '/dashboard'
    | '/individual-expenses'
    | '/settings'
    | '/settle-up'
    | '/add-expense/$userId'
    | '/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AddExpenseRoute: typeof AddExpenseRouteWithChildren
  CreateGroupRoute: typeof CreateGroupRoute
  DashboardRoute: typeof DashboardRoute
  IndividualExpensesRoute: typeof IndividualExpensesRoute
  SettingsRoute: typeof SettingsRoute
  SettleUpRoute: typeof SettleUpRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settle-up': {
      id: '/settle-up'
      path: '/settle-up'
      fullPath: '/settle-up'
      preLoaderRoute: typeof SettleUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individual-expenses': {
      id: '/individual-expenses'
      path: '/individual-expenses'
      fullPath: '/individual-expenses'
      preLoaderRoute: typeof IndividualExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-group': {
      id: '/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof CreateGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-expense': {
      id: '/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AddExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-expense/$userId': {
      id: '/add-expense/$userId'
      path: '/$userId'
      fullPath: '/add-expense/$userId'
      preLoaderRoute: typeof AddExpenseUserIdRouteImport
      parentRoute: typeof AddExpenseRoute
    }
  }
}

interface AddExpenseRouteChildren {
  AddExpenseUserIdRoute: typeof AddExpenseUserIdRoute
}

const AddExpenseRouteChildren: AddExpenseRouteChildren = {
  AddExpenseUserIdRoute: AddExpenseUserIdRoute,
}

const AddExpenseRouteWithChildren = AddExpenseRoute._addFileChildren(
  AddExpenseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AddExpenseRoute: AddExpenseRouteWithChildren,
  CreateGroupRoute: CreateGroupRoute,
  DashboardRoute: DashboardRoute,
  IndividualExpensesRoute: IndividualExpensesRoute,
  SettingsRoute: SettingsRoute,
  SettleUpRoute: SettleUpRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
