create table "public"."user_contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "contact_user_id" bigint not null
);


alter table "public"."user_contacts" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "avatar_url" text,
    "payment_message" text
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX user_contacts_pkey ON public.user_contacts USING btree (id);

CREATE UNIQUE INDEX user_pkey ON public.users USING btree (id);

alter table "public"."user_contacts" add constraint "user_contacts_pkey" PRIMARY KEY using index "user_contacts_pkey";

alter table "public"."users" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."user_contacts" add constraint "user_contacts_contact_user_id_fkey" FOREIGN KEY (contact_user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."user_contacts" validate constraint "user_contacts_contact_user_id_fkey";

alter table "public"."user_contacts" add constraint "user_contacts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."user_contacts" validate constraint "user_contacts_user_id_fkey";

alter table "public"."users" add constraint "users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_user_id_fkey";

grant delete on table "public"."user_contacts" to "anon";

grant insert on table "public"."user_contacts" to "anon";

grant references on table "public"."user_contacts" to "anon";

grant select on table "public"."user_contacts" to "anon";

grant trigger on table "public"."user_contacts" to "anon";

grant truncate on table "public"."user_contacts" to "anon";

grant update on table "public"."user_contacts" to "anon";

grant delete on table "public"."user_contacts" to "authenticated";

grant insert on table "public"."user_contacts" to "authenticated";

grant references on table "public"."user_contacts" to "authenticated";

grant select on table "public"."user_contacts" to "authenticated";

grant trigger on table "public"."user_contacts" to "authenticated";

grant truncate on table "public"."user_contacts" to "authenticated";

grant update on table "public"."user_contacts" to "authenticated";

grant delete on table "public"."user_contacts" to "service_role";

grant insert on table "public"."user_contacts" to "service_role";

grant references on table "public"."user_contacts" to "service_role";

grant select on table "public"."user_contacts" to "service_role";

grant trigger on table "public"."user_contacts" to "service_role";

grant truncate on table "public"."user_contacts" to "service_role";

grant update on table "public"."user_contacts" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";



