alter table "public"."group_members" drop constraint "group_members_pkey";

alter table "public"."user_contacts" drop constraint "user_contacts_pkey";

drop index if exists "public"."group_members_pkey";

drop index if exists "public"."user_contacts_pkey";

create table "public"."audit" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "expense_id" bigint not null,
    "user_id" bigint not null,
    "action" text not null default ''::text,
    "details" text
);


create table "public"."expense_members" (
    "expense_id" bigint not null,
    "user_id" bigint not null,
    "amount_share" numeric not null
);


create table "public"."expenses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "group_id" bigint,
    "description" text not null,
    "amount" numeric not null,
    "user_paid" bigint not null
);


create table "public"."settlements" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "group_id" bigint,
    "user_paid" bigint,
    "user_received" bigint
);


alter table "public"."group_members" drop column "created_at";

alter table "public"."group_members" drop column "id";

alter table "public"."groups" add column "created_by" bigint;

alter table "public"."user_contacts" drop column "created_at";

alter table "public"."user_contacts" drop column "id";

CREATE UNIQUE INDEX audit_pkey ON public.audit USING btree (id);

CREATE UNIQUE INDEX expense_members_pkey ON public.expense_members USING btree (expense_id, user_id);

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);

CREATE UNIQUE INDEX settlements_pkey ON public.settlements USING btree (id);

CREATE UNIQUE INDEX group_members_pkey ON public.group_members USING btree (group_id, user_id);

CREATE UNIQUE INDEX user_contacts_pkey ON public.user_contacts USING btree (user_id, contact_user_id);

alter table "public"."audit" add constraint "audit_pkey" PRIMARY KEY using index "audit_pkey";

alter table "public"."expense_members" add constraint "expense_members_pkey" PRIMARY KEY using index "expense_members_pkey";

alter table "public"."expenses" add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."settlements" add constraint "settlements_pkey" PRIMARY KEY using index "settlements_pkey";

alter table "public"."group_members" add constraint "group_members_pkey" PRIMARY KEY using index "group_members_pkey";

alter table "public"."user_contacts" add constraint "user_contacts_pkey" PRIMARY KEY using index "user_contacts_pkey";

alter table "public"."audit" add constraint "audit_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE not valid;

alter table "public"."audit" validate constraint "audit_expense_id_fkey";

alter table "public"."audit" add constraint "audit_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."audit" validate constraint "audit_user_id_fkey";

alter table "public"."expense_members" add constraint "expense_members_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE not valid;

alter table "public"."expense_members" validate constraint "expense_members_expense_id_fkey";

alter table "public"."expense_members" add constraint "expense_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."expense_members" validate constraint "expense_members_user_id_fkey";

alter table "public"."expenses" add constraint "expenses_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_group_id_fkey";

alter table "public"."expenses" add constraint "expenses_user_paid_fkey" FOREIGN KEY (user_paid) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_user_paid_fkey";

alter table "public"."groups" add constraint "groups_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) not valid;

alter table "public"."groups" validate constraint "groups_created_by_fkey";

alter table "public"."settlements" add constraint "settlements_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE not valid;

alter table "public"."settlements" validate constraint "settlements_group_id_fkey";

alter table "public"."settlements" add constraint "settlements_user_paid_fkey" FOREIGN KEY (user_paid) REFERENCES users(id) not valid;

alter table "public"."settlements" validate constraint "settlements_user_paid_fkey";

alter table "public"."settlements" add constraint "settlements_user_received_fkey" FOREIGN KEY (user_received) REFERENCES users(id) not valid;

alter table "public"."settlements" validate constraint "settlements_user_received_fkey";

grant delete on table "public"."audit" to "anon";

grant insert on table "public"."audit" to "anon";

grant references on table "public"."audit" to "anon";

grant select on table "public"."audit" to "anon";

grant trigger on table "public"."audit" to "anon";

grant truncate on table "public"."audit" to "anon";

grant update on table "public"."audit" to "anon";

grant delete on table "public"."audit" to "authenticated";

grant insert on table "public"."audit" to "authenticated";

grant references on table "public"."audit" to "authenticated";

grant select on table "public"."audit" to "authenticated";

grant trigger on table "public"."audit" to "authenticated";

grant truncate on table "public"."audit" to "authenticated";

grant update on table "public"."audit" to "authenticated";

grant delete on table "public"."audit" to "service_role";

grant insert on table "public"."audit" to "service_role";

grant references on table "public"."audit" to "service_role";

grant select on table "public"."audit" to "service_role";

grant trigger on table "public"."audit" to "service_role";

grant truncate on table "public"."audit" to "service_role";

grant update on table "public"."audit" to "service_role";

grant delete on table "public"."expense_members" to "anon";

grant insert on table "public"."expense_members" to "anon";

grant references on table "public"."expense_members" to "anon";

grant select on table "public"."expense_members" to "anon";

grant trigger on table "public"."expense_members" to "anon";

grant truncate on table "public"."expense_members" to "anon";

grant update on table "public"."expense_members" to "anon";

grant delete on table "public"."expense_members" to "authenticated";

grant insert on table "public"."expense_members" to "authenticated";

grant references on table "public"."expense_members" to "authenticated";

grant select on table "public"."expense_members" to "authenticated";

grant trigger on table "public"."expense_members" to "authenticated";

grant truncate on table "public"."expense_members" to "authenticated";

grant update on table "public"."expense_members" to "authenticated";

grant delete on table "public"."expense_members" to "service_role";

grant insert on table "public"."expense_members" to "service_role";

grant references on table "public"."expense_members" to "service_role";

grant select on table "public"."expense_members" to "service_role";

grant trigger on table "public"."expense_members" to "service_role";

grant truncate on table "public"."expense_members" to "service_role";

grant update on table "public"."expense_members" to "service_role";

grant delete on table "public"."expenses" to "anon";

grant insert on table "public"."expenses" to "anon";

grant references on table "public"."expenses" to "anon";

grant select on table "public"."expenses" to "anon";

grant trigger on table "public"."expenses" to "anon";

grant truncate on table "public"."expenses" to "anon";

grant update on table "public"."expenses" to "anon";

grant delete on table "public"."expenses" to "authenticated";

grant insert on table "public"."expenses" to "authenticated";

grant references on table "public"."expenses" to "authenticated";

grant select on table "public"."expenses" to "authenticated";

grant trigger on table "public"."expenses" to "authenticated";

grant truncate on table "public"."expenses" to "authenticated";

grant update on table "public"."expenses" to "authenticated";

grant delete on table "public"."expenses" to "service_role";

grant insert on table "public"."expenses" to "service_role";

grant references on table "public"."expenses" to "service_role";

grant select on table "public"."expenses" to "service_role";

grant trigger on table "public"."expenses" to "service_role";

grant truncate on table "public"."expenses" to "service_role";

grant update on table "public"."expenses" to "service_role";

grant delete on table "public"."settlements" to "anon";

grant insert on table "public"."settlements" to "anon";

grant references on table "public"."settlements" to "anon";

grant select on table "public"."settlements" to "anon";

grant trigger on table "public"."settlements" to "anon";

grant truncate on table "public"."settlements" to "anon";

grant update on table "public"."settlements" to "anon";

grant delete on table "public"."settlements" to "authenticated";

grant insert on table "public"."settlements" to "authenticated";

grant references on table "public"."settlements" to "authenticated";

grant select on table "public"."settlements" to "authenticated";

grant trigger on table "public"."settlements" to "authenticated";

grant truncate on table "public"."settlements" to "authenticated";

grant update on table "public"."settlements" to "authenticated";

grant delete on table "public"."settlements" to "service_role";

grant insert on table "public"."settlements" to "service_role";

grant references on table "public"."settlements" to "service_role";

grant select on table "public"."settlements" to "service_role";

grant trigger on table "public"."settlements" to "service_role";

grant truncate on table "public"."settlements" to "service_role";

grant update on table "public"."settlements" to "service_role";



